# Generated by Django 3.2.9 on 2021-11-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211123_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='views',
        ),
    ]
